volumes:
  postgres_data: {}
  postgres_data_backups: {}
  redis_data: {}

services:
  poc-django-reactjs-base:
    build:
      context: ..
      dockerfile: ./containers/compose/local/django/Dockerfile
    image: poc-django-reactjs
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}'
    command: /start

  poc-django-reactjs:
    extends: poc-django-reactjs-base
    # NOTE: Any other service that is based on poc-django-reactjs-base should set:
    # build: !reset null
    container_name: django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - '${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}'
    command: /start

  celeryworker:
    extends: poc-django-reactjs-base
    hostname: celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    hostname: celerybeat
    extends: poc-django-reactjs-base
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: poc_django_production_postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    command: postgres -p ${POSTGRES_PORT:-5432}

  redis:
    image: docker.io/redis:6
    container_name: redis
    ports:
      - '${REDIS_PORT:-6379}:${REDIS_PORT:-6379}'
    volumes:
      - redis_data:/data

  flower:
    extends: poc-django-reactjs-base
    image: flower
    hostname: flower
    ports:
      - '${CELERY_FLOWRER_PORT:-25555}:${CELERY_FLOWRER_PORT:-25555}'
    command: /start-flower
