volumes:
  postgres_data: {}
  postgres_data_backups: {}
  redis_data: {}

services:
  poc-django-reactjs:
    extends:
      file: compose.base.yml
      service: poc-django-reactjs
    volumes:
      - .:/app:z

  postgres:
    extends:
      file: compose.base.yml
      service: postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    hostname: mailpit
    ports:
      - "${MAILPIT_PORT:-8025}:${MAILPIT_PORT:-8025}"

  redis:
    extends:
      file: compose.base.yml
      service: redis

  celeryworker:
    extends:
      file: compose.base.yml
      service: celeryworker
    volumes:
      - .:/app:z

  celerybeat:
    extends:
      file: compose.base.yml
      service: celerybeat
    volumes:
      - .:/app:z

  flower:
    extends:
      file: compose.base.yml
      service: flower
